### ISSUE TITLE
What do the values mean?

### ISSUE THREAD

**Issue by cadop** [gytsto/hyper_v_gpu_passthrough#1]
Hi, since you have this script on github, I was wondering if you knew what any of the values/numbers used in it mean?

https://github.com/gytsto/hyper_v_gpu_passthrough/blob/27498d1066b56ff0da6d6bafca826cc67605cf27/gpu_passthrough.ps1#L5

**Comment by gytsto** [comment]
https://learn.microsoft.com/en-us/powershell/module/hyper-v/set-vmgpupartitionadapter?view=windowsserver2022-ps
